version: '3'
volumes:
  Mini_ingredients:
    external: true

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - '5000:5000'
    env_file:
      - ../../.env
    environment:
      PORT: 5000
    entrypoint:
      - /usr/app/docker/dev/entrypoint.sh
    command:
      - yarn
      - start
